name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar o .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: '--debug'

    - name: Docker Login
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u Fekler --password-stdin

    - name: Build Docker Image for ARM64
      uses: docker/build-push-action@v3
      with:
        context: ./LearningTDD
        file: ./LearningTDD/Dockerfile
        push: true
        tags: ghcr.io/fekler/learningtdd/learningtdd:latest
        platforms: linux/arm64

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy para a VM via SSH
      uses: appleboy/ssh-action@v0.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u Fekler --password-stdin
          sudo docker pull ghcr.io/fekler/learningtdd/learningtdd:latest
          sudo docker stop learningtdd || true
          sudo docker rm learningtdd || true
          sudo docker run -d -p 8080:8080 --name learningtdd --network tdd_network ghcr.io/fekler/learningtdd/learningtdd:latest
