name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar o .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Set Environment Variables
      run: echo "ConnectionStrings__DefaultConnection=${{ secrets.CONNECTION_STRING }}" >> $GITHUB_ENV

    - name: Restaurar dependências
      run: dotnet restore ./LearningTDD/LearningTDD.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release ./LearningTDD/LearningTDD.sln

    - name: Testar
      run: dotnet test --no-build --configuration Release --verbosity normal ./LearningTDD/LearningTDD.sln


    - name: Buildar a imagem Docker
      run: docker build -t ghcr.io/fekler/learningtdd/learningtdd:latest -f LearningTDD/Dockerfile LearningTDD

    - name: login
      run: docker login --username Fekler --password ${{ secrets.GHCR_PAT }} ghcr.io

    - name: Push da imagem para o GitHub Packages
      run: docker push ghcr.io/fekler/learningtdd/learningtdd:latest
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy para a VM via SSH
      uses: appleboy/ssh-action@v0.1.17
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Atualizar a imagem Docker
          docker pull ghcr.io/fekler/learningtdd/learningtdd:latest

          # Parar e remover o container existente, se houver
          docker stop learningtdd || true
          docker rm learningtdd || true

          # Rodar o novo container
          docker run -d -p 8080:8080  --name learningtdd --network tdd_network ghcr.io/fekler/learningtdd/learningtdd:latest
