name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar o .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Set Environment Variables
      run: echo "ConnectionStrings__DefaultConnection=${{ secrets.CONNECTION_STRING }}" >> $GITHUB_ENV

    - name: Restaurar dependências
      run: dotnet restore ./LearningTDD/LearningTDD.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release ./LearningTDD/LearningTDD.sln

    - name: Testar
      run: dotnet test --no-build --configuration Release --verbosity normal ./LearningTDD/LearningTDD.sln


    # - name: Buildar a imagem Docker
    #   run: docker build -t ghcr.io/fekler/learningtdd/learningtdd:latest -f LearningTDD/Dockerfile LearningTDD

    - name: login
      run: docker login --username Fekler --password ${{ secrets.GHCR_PAT }} ghcr.io

    # - name: Push da imagem para o GitHub Packages
    #   run: docker push ghcr.io/fekler/learningtdd/learningtdd:latest

    - name: Buildar a imagem Docker
      run: |
       docker buildx create --use
       docker buildx inspect --bootstrap
       docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/fekler/learningtdd/learningtdd:latest -f LearningTDD/Dockerfile LearningTDD --push
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy para a VM via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}

        script: |

          echo ${{ secrets.GHCR_DOWNLOAD }} | docker login ghcr.io -u fekler --password-stdin

          # Atualizar a imagem Docker
          sudo docker pull ghcr.io/fekler/learningtdd/learningtdd:latest

          # Parar e remover o container existente, se houver
          sudo docker stop learningtdd || true
          sudo docker rm learningtdd || true

          # Rodar o novo container
          sudo docker run -d -p 8080:8080  --name learningtdd --network tdd_network ghcr.io/fekler/learningtdd/learningtdd:latest
          exit